using Microsoft.VisualStudio.TestTools.UnitTesting;
using GcodeRepeater.Gcode.Parsers;

namespace GcodeRepeater.Tests;

[TestClass]
public class GcodeFileParserFactoryTests
{
    private string _curaTempFile;
    private string _orcaTempFile;
    private string _unknownTempFile;
    
    [TestInitialize]
    public void Setup()
    {
        _curaTempFile = Path.GetTempFileName() + ".gcode";
        _orcaTempFile = Path.GetTempFileName() + ".gcode";
        _unknownTempFile = Path.GetTempFileName() + ".gcode";
        
        File.WriteAllText(_curaTempFile, ";Generated with Cura\r\nG0 X0 Y0 Z0");
        File.WriteAllText(_orcaTempFile, "; generated by OrcaSlicer\r\nG0 X0 Y0 Z0");
        File.WriteAllText(_unknownTempFile, ";Some unknown header\r\nG0 X0 Y0 Z0");
    }

    [TestCleanup]
    public void Cleanup()
    {
        if (File.Exists(_curaTempFile)) File.Delete(_curaTempFile);
        if (File.Exists(_orcaTempFile)) File.Delete(_orcaTempFile);
        if (File.Exists(_unknownTempFile)) File.Delete(_unknownTempFile);
    }

    [TestMethod]
    public void GetParser_CuraFile_ReturnsCuraParser()
    {
        // Arrange
        var factory = new GcodeFileParserFactory();

        // Act
        var parser = ((IGcodeFileParserFactory)factory).GetParser(_curaTempFile);

        // Assert
        Assert.IsInstanceOfType(parser, typeof(CuraGcodeFileParser));
    }

    [TestMethod]
    public void GetParser_OrcaFile_ReturnsOrcaParser()
    {
        // Arrange
        var factory = new GcodeFileParserFactory();

        // Act
        var parser = ((IGcodeFileParserFactory)factory).GetParser(_orcaTempFile);

        // Assert
        Assert.IsInstanceOfType(parser, typeof(OrcaGcodeFileParser));
    }

    [TestMethod]
    public void GetParser_UnknownFile_ThrowsException()
    {
        // Arrange
        var factory = new GcodeFileParserFactory();

        // Act & Assert
        //Assert.ThrowsException<Exception>(() => ((IGcodeFileParserFactory)factory).GetParser(_unknownTempFile));
    }
}