namespace GcodeRepeater.Gcode.Parsers
{
    internal class GcodeFileParserFactory : IGcodeFileParserFactory
    {
        IGcodeFileParser IGcodeFileParserFactory.GetParser(string path)
        {
            using (var streamReader = File.OpenText(path))
            {
                string? str;
                do
                {
                    str = streamReader.ReadLine();
                    if (str == null)
                    {
                        break;
                    }

                    if (str.StartsWith(";"))
                    {
                        if (str.StartsWith(";Generated with Cura", StringComparison.InvariantCultureIgnoreCase))
                        {
                            return new CuraGcodeFileParser();
                        }
                        if (str.StartsWith("; generated by OrcaSlicer", StringComparison.InvariantCultureIgnoreCase))
                        {
                            return new OrcaGcodeFileParser();
                        }
                    }
                } while (str != null);

                throw new Exception("Unknown Gcode generator");
            }
        }
    }
}